apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
  namespace: nginx-proxy
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
  namespace: nginx-proxy
spec:
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
      - image: shanty0205/my-nginx-proxy:latest
        name: nginx-proxy
        ports:
        - containerPort: 80
